export enum AsyncValidatorNames {
	ResultDependantOnCustomDefects = 'resultDependantOnCustomDefects',
	ResultDependantOnRequiredStandards = 'resultDependantOnRequiredStandards',
	UpdateTestStationDetails = 'updateTestStationDetails',
	UpdateTesterDetails = 'updateTesterDetails',
	RequiredIfNotFail = 'requiredIfNotfail',
	RequiredIfNotAbandoned = 'requiredIfNotabandoned',
	RequiredIfNotResultAndSiblingEquals = 'requiredIfNotResultAndSiblingEquals',
	RequiredIfNotResult = 'requiredIfNotResult',
	HideIfEqualsWithCondition = 'hideIfEqualsWithCondition',
	PassResultDependantOnCustomDefects = 'passResultDependantOnCustomDefects',
	RequiredWhenCarryingDangerousGoods = 'requiredWhenCarryingDangerousGoods',
	Custom = 'custom',
  FilterEuCategoryOnVehicleType = 'filterEuCategoryOnVehicleType',
}
