/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AdrDetailsTankTankDetailsTc2Details {
	/**
	 * Optional. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
	 */
	tc2Type?: AdrDetailsTankTankDetailsTc2Details.Tc2TypeEnum;
	/**
	 * Optional. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
	 */
	tc2IntermediateApprovalNo?: string;
	/**
	 * Optional. Date(YYYY-MM-DD). Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
	 */
	tc2IntermediateExpiryDate?: string;
}
export namespace AdrDetailsTankTankDetailsTc2Details {
	export type Tc2TypeEnum = 'initial';
	export const Tc2TypeEnum = {
		Initial: 'initial' as Tc2TypeEnum,
	};
}
