export const environment = {
	production: true,
	TARGET_ENV: 'prod',
	RemoveAADFullAccessRole: true,
	EnableDevTools: false,
	VTM_CLIENT_ID: '',
	VTM_AUTHORITY_ID: '',
	VTM_REDIRECT_URI: '/',
	VTM_API_URI: '',
	VTM_API_CLIENT_ID: '',
	LOGS_API_KEY: '',
	DOCUMENT_RETRIEVAL_API_KEY: '',
	FEEDBACK_URI: '',
	SENTRY_DSN: '',
	VTM_GTM_CONTAINER_ID: '',
	VTM_GTM_MEASUREMENT_ID: '',
};
