export const environment = {
  production: true,
  isDevelop: false,
  isIntegration: false,
  isPreProd: false,
  RemoveAADFullAccessRole: true,
  EnableDevTools: false,
  VTM_CLIENT_ID: '',
  VTM_AUTHORITY_ID: '',
  VTM_REDIRECT_URI: '/',
  VTM_API_URI: '',
  VTM_API_CLIENT_ID: '',
  DOCUMENT_RETRIEVAL_API_KEY: '',
  FEEDBACK_URI: '',
  SENTRY_DSN: '',
};
