/**
 * Test Types Microservice
 * This is the API spec for the test types microservice. This microservice has one endpoint which will get all of the test type data.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Test type
 */
export interface TestTypeInfo {
  /**
     * Unique identifier
     */
  id?: string;
  testTypeClassification?: TestTypeInfo.TestTypeClassificationEnum;
  defaultTestCode?: string;
  linkedTestCode?: string;
}
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace TestTypeInfo {
  export type TestTypeClassificationEnum = 'Annual With Certificate' | 'Annual No Certificate' | 'Non Annual';
  export const TestTypeClassificationEnum = {
    AnnualWithCertificate: 'Annual With Certificate' as TestTypeClassificationEnum,
    AnnualNoCertificate: 'Annual No Certificate' as TestTypeClassificationEnum,
    NonAnnual: 'Non Annual' as TestTypeClassificationEnum,
  };
}
