/**
 * Test Types Microservice
 * This is the API spec for the test types microservice. This microservice has one endpoint which will get all of the test type data.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mdclarke@deloitte.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestTypeCategory } from './testTypeCategory';
import { TestType } from './testType';


/**
 * @type TestTypeCategoryNextTestTypesOrCategoriesInner
 * @export
 */
export type TestTypeCategoryNextTestTypesOrCategoriesInner = TestType | TestTypeCategory;

