/**
 * Reference Data Microservice
 * This is the API spec for the reference data service. The reference data will be stored in a AWS DynamoDB database.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmptyObject } from './emptyObject';
import { ReferenceDataItem } from './referenceDataItem';

export type ReferenceDataItemApiResponse = ReferenceDataItem | EmptyObject;