import { Injectable, inject } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import {
	DefectDetailsSchema,
	EUVehicleCategory,
	EmissionStandards,
	FuelType,
	MediaSchema,
	OdometerReadingUnits,
	SpecialistCustomDefectsSchema,
	SpecialistCustomDefectsSchemaPut,
	TestResults,
	TestSources,
	TestStationTypes,
	TestStatus,
	TypeOfTest,
	VehicleType,
} from '@dvsa/cvs-type-definitions/types/v1/test-result';

@Injectable({
	providedIn: 'root',
})
export class TestService {
	fb = inject(FormBuilder);

	form = this.fb.group({
		testResultId: this.fb.nonNullable.control<string>(''),
		testStationName: this.fb.control<string | null>(null),
		testStationPNumber: this.fb.control<string | null>(null),
		testStationType: this.fb.nonNullable.control<TestStationTypes>('atf' as TestStationTypes),
		testerName: this.fb.control<string | null>(null),
		testerStaffId: this.fb.nonNullable.control<string>(''),
		testerEmailAddress: this.fb.control<string | null>(null),
		testStartTimestamp: this.fb.nonNullable.control<string>(''),
		testEndTimestamp: this.fb.nonNullable.control<string>(''),
		testStatus: this.fb.nonNullable.control<TestStatus>('submitted' as TestStatus),
		reasonForCancellation: this.fb.control<string | null>(null),
		systemNumber: this.fb.nonNullable.control<string>(''),
		vrm: this.fb.nonNullable.control<string | undefined>(undefined),
		trailerId: this.fb.nonNullable.control<string | undefined>(undefined),
		vin: this.fb.nonNullable.control<string>(''),
		vehicleClass: this.fb.group({
			code: this.fb.control<string>(''),
			description: this.fb.control<string>(''),
		}),
		vehicleSubclass: this.fb.nonNullable.control<string[] | undefined>(undefined),
		vehicleType: this.fb.nonNullable.control<VehicleType>('car'),
		vehicleConfiguration: this.fb.nonNullable.control<string>(''),
		odometerReading: this.fb.control<number | null | undefined>(undefined),
		odometerReadingUnits: this.fb.control<OdometerReadingUnits | null | undefined>(undefined),
		preparerId: this.fb.control<string | null>(null),
		preparerName: this.fb.control<string | null>(null),
		euVehicleCategory: this.fb.control<EUVehicleCategory | null>(null),
		countryOfRegistration: this.fb.control<string | null>(null),
		noOfAxles: this.fb.control<number | null>(null),
		numberOfWheelsDriven: this.fb.control<number | null>(null),
		vehicleSize: this.fb.nonNullable.control<string | undefined>(undefined),
		numberOfSeats: this.fb.nonNullable.control<number | undefined>(undefined),
		regnDate: this.fb.control<string | null | undefined>(undefined),
		firstUseDate: this.fb.control<string | null | undefined>(undefined),
		media: this.fb.nonNullable.control<MediaSchema[]>([]),
		reasonForCreation: this.fb.nonNullable.control<string>(''),
		createdAt: this.fb.control<string | null>(null),
		createdByEmailAddress: this.fb.nonNullable.control<string>(''),
		createdByName: this.fb.nonNullable.control<string>(''),
		createdById: this.fb.nonNullable.control<string>(''),
		lastUpdatedAt: this.fb.control<string | null>(null),
		lastUpdatedByEmailAddress: this.fb.nonNullable.control<string>(''),
		lastUpdatedByName: this.fb.nonNullable.control<string>(''),
		lastUpdatedById: this.fb.nonNullable.control<string>(''),
		shouldEmailCertificate: this.fb.nonNullable.control<string>(''),
		contingencyTestNumber: this.fb.control<string | null>(null),
		typeOfTest: this.fb.nonNullable.control<TypeOfTest>('contingency' as TypeOfTest),
		source: this.fb.nonNullable.control<TestSources>('vtm' as TestSources),
		make: this.fb.control<string | null>(null),
		model: this.fb.control<string | null>(null),
		bodyType: this.fb.group({
			code: this.fb.control<string>(''),
			description: this.fb.control<string>(''),
		}),
		vehicleId: this.fb.control<string | null>(null),
		testVersion: this.fb.nonNullable.control<string>(''),
		deletionFlag: this.fb.nonNullable.control<boolean>(false),
		recalls: this.fb.group({
			hasRecall: this.fb.control<boolean>(false),
			manufacturer: this.fb.control<string | null>(null),
		}),
		testTypes: this.fb.array([
			this.fb.group({
				testTypeName: this.fb.control<string | null>(null),
				name: this.fb.control<string>(''),
				testTypeId: this.fb.control<string>(''),
				certificateNumber: this.fb.control<string | null>(null),
				secondaryCertificateNumber: this.fb.control<string | null>(null),
				testTypeStartTimestamp: this.fb.control<string | null>(null),
				testTypeEndTimestamp: this.fb.control<string | null>(null),
				testResult: this.fb.control<TestResults | null>(null),
				prohibitionIssued: this.fb.control<boolean | null>(null),
				reasonForAbandoning: this.fb.control<string | null>(null),
				additionalNotesRecorded: this.fb.control<string | null>(null),
				additionalCommentsForAbandon: this.fb.control<string | null>(null),
				numberOfSeatbeltsFitted: this.fb.control<number | null | undefined>(undefined),
				lastSeatbeltInstallationCheckDate: this.fb.control<string | null | undefined>(undefined),
				seatbeltInstallationCheckDate: this.fb.control<boolean | null | undefined>(undefined),
				testExpiryDate: this.fb.control<string | undefined>(undefined),
				testAnniversaryDate: this.fb.control<string | null | undefined>(undefined),
				modType: this.fb.group({
					code: this.fb.control<string>(''),
					description: this.fb.control<string>(''),
				}),
				emissionStandard: this.fb.control<EmissionStandards | null | undefined>(undefined),
				fuelType: this.fb.control<FuelType | null | undefined>(undefined),
				modificationTypeUsed: this.fb.control<string | null | undefined>(undefined),
				smokeTestKLimitApplied: this.fb.control<string | null | undefined>(undefined),
				particulateTrapFitted: this.fb.control<string | null | undefined>(undefined),
				particulateTrapSerialNumber: this.fb.control<string | null | undefined>(undefined),
				defects: this.fb.control<DefectDetailsSchema[]>([]),
				customDefects: this.fb.control<SpecialistCustomDefectsSchema[] | undefined>(undefined),
				requiredStandards: this.fb.control<SpecialistCustomDefectsSchemaPut[] | undefined>(undefined),
				testNumber: this.fb.control<string | null>(null),
				reapplicationDate: this.fb.control<string | null | undefined>(undefined),
				testCode: this.fb.control<string | null>(null),
				lastUpdatedAt: this.fb.control<string | null>(null),
				createdAt: this.fb.control<string | null>(null),
				testTypeClassification: this.fb.control<string | null>(null),
				deletionFlag: this.fb.control<boolean | null>(null),
				centralDocs: this.fb.group({
					issueRequired: this.fb.control<boolean>(false),
					notes: this.fb.control<string>(''),
					reasonsForIssue: this.fb.control<string[]>([]),
				}),
			}),
		]),
	});
}
