import { Injectable, inject } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import {
	DefectDetailsSchema,
	EUVehicleCategory,
	EmissionStandards,
	FuelType,
	MediaSchema,
	ModTypeSchema,
	OdometerReadingUnits,
	RecallsSchema,
	SpecialistCustomDefectsSchema,
	SpecialistCustomDefectsSchemaPut,
	TestResults,
	TestSources,
	TestStationTypes,
	TestStatus,
	TypeOfTest,
	VehicleType,
} from '@dvsa/cvs-type-definitions/types/v1/test-result';

@Injectable({
	providedIn: 'root',
})
export class TestService {
	fb = inject(FormBuilder);

	form = this.fb.group({
		testResultId: this.fb.nonNullable.control<string>(''),
		testStationName: this.fb.control<string | null>(null),
		testStationPNumber: this.fb.control<string | null>(null),
		testStationType: this.fb.nonNullable.control<TestStationTypes | null>({ value: null, disabled: true }),
		testerName: this.fb.control<string | null>(null),
		testerStaffId: this.fb.nonNullable.control<string>(''),
		testerEmailAddress: this.fb.control<string | null>(null),
		testStartTimestamp: this.fb.nonNullable.control<string>(''),
		testEndTimestamp: this.fb.nonNullable.control<string>(''),
		testStatus: this.fb.nonNullable.control<TestStatus>('submitted' as TestStatus),
		reasonForCancellation: this.fb.control<string | null>(null),
		systemNumber: this.fb.nonNullable.control<string>(''),
		vrm: this.fb.nonNullable.control<string | undefined>({ value: undefined, disabled: false }),
		trailerId: this.fb.nonNullable.control<string | undefined>({ value: undefined, disabled: false }),
		vin: this.fb.nonNullable.control<string>(''),
		vehicleClass: this.fb.group({
			code: this.fb.nonNullable.control<string>(''),
			description: this.fb.nonNullable.control<string>(''),
		}),
		vehicleSubclass: this.fb.nonNullable.control<string[] | undefined>({ value: undefined, disabled: false }),
		vehicleType: this.fb.nonNullable.control<VehicleType>('car'),
		vehicleConfiguration: this.fb.nonNullable.control<string>(''),
		odometerReading: this.fb.control<number | null | undefined>({ value: undefined, disabled: false }),
		odometerReadingUnits: this.fb.control<OdometerReadingUnits | null | undefined>({
			value: undefined,
			disabled: false,
		}),
		preparerId: this.fb.control<string | null>(null),
		preparerName: this.fb.control<string | null>(null),
		euVehicleCategory: this.fb.control<EUVehicleCategory | null>(null),
		countryOfRegistration: this.fb.control<string | null>(null),
		noOfAxles: this.fb.control<number | null>(null),
		numberOfWheelsDriven: this.fb.control<number | null>(null),
		vehicleSize: this.fb.nonNullable.control<string | undefined>({ value: undefined, disabled: false }),
		numberOfSeats: this.fb.nonNullable.control<number | undefined>({ value: undefined, disabled: false }),
		regnDate: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
		firstUseDate: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
		media: this.fb.nonNullable.control<MediaSchema[] | undefined>({ value: undefined, disabled: false }),
		reasonForCreation: this.fb.nonNullable.control<string>(''),
		createdAt: this.fb.control<string | null>(null),
		createdByEmailAddress: this.fb.nonNullable.control<string | undefined>({ value: undefined, disabled: false }),
		createdByName: this.fb.nonNullable.control<string>(''),
		createdById: this.fb.nonNullable.control<string>(''),
		lastUpdatedAt: this.fb.control<string | null>(null),
		lastUpdatedByEmailAddress: this.fb.nonNullable.control<string | undefined>({ value: undefined, disabled: false }),
		lastUpdatedByName: this.fb.nonNullable.control<string>(''),
		lastUpdatedById: this.fb.nonNullable.control<string>(''),
		contingencyTestNumber: this.fb.control<string | null>(null),
		typeOfTest: this.fb.nonNullable.control<TypeOfTest>('contingency' as TypeOfTest),
		source: this.fb.nonNullable.control<TestSources>('vtm' as TestSources),
		make: this.fb.control<string | null>(null),
		model: this.fb.control<string | null>(null),
		bodyType: this.fb.group({
			code: this.fb.control<string>(''),
			description: this.fb.control<string>(''),
		}),
		recalls: this.fb.control<RecallsSchema | undefined>({ value: undefined, disabled: false }),
		testTypes: this.fb.array([
			this.fb.group({
				testTypeName: this.fb.control<string | null>(null),
				name: this.fb.control<string>(''),
				testTypeId: this.fb.control<string>(''),
				certificateNumber: this.fb.control<string | null>(null),
				secondaryCertificateNumber: this.fb.control<string | null>(null),
				testTypeStartTimestamp: this.fb.control<string | null>(null),
				testTypeEndTimestamp: this.fb.control<string | null>(null),
				testResult: this.fb.control<TestResults | null>(null),
				prohibitionIssued: this.fb.control<boolean | null>(null),
				reasonForAbandoning: this.fb.control<string | null>(null),
				additionalNotesRecorded: this.fb.control<string | null>(null),
				additionalCommentsForAbandon: this.fb.control<string | null>(null),
				numberOfSeatbeltsFitted: this.fb.control<number | null | undefined>({ value: undefined, disabled: false }),
				lastSeatbeltInstallationCheckDate: this.fb.control<string | null | undefined>({
					value: undefined,
					disabled: false,
				}),
				seatbeltInstallationCheckDate: this.fb.control<boolean | null | undefined>({
					value: undefined,
					disabled: false,
				}),
				testExpiryDate: this.fb.control<string | undefined>({ value: undefined, disabled: false }),
				testAnniversaryDate: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				modType: this.fb.control<ModTypeSchema | undefined>({ value: undefined, disabled: false }),
				emissionStandard: this.fb.control<EmissionStandards | null | undefined>({ value: undefined, disabled: false }),
				fuelType: this.fb.control<FuelType | null | undefined>({ value: undefined, disabled: false }),
				modificationTypeUsed: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				smokeTestKLimitApplied: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				particulateTrapFitted: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				particulateTrapSerialNumber: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				defects: this.fb.nonNullable.control<DefectDetailsSchema[]>([]),
				customDefects: this.fb.control<SpecialistCustomDefectsSchema[] | undefined>([]),
				requiredStandards: this.fb.control<SpecialistCustomDefectsSchemaPut[] | undefined>({
					value: undefined,
					disabled: false,
				}),
				testNumber: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				reapplicationDate: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				testCode: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				createdAt: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				testTypeClassification: this.fb.control<string | null | undefined>({ value: undefined, disabled: false }),
				centralDocs: this.fb.group({
					issueRequired: this.fb.control<boolean>(false),
					notes: this.fb.control<string>(' '),
					reasonsForIssue: this.fb.control<string[]>([]),
				}),
			}),
		]),
	});
}
