export enum ValidatorNames {
  CustomPattern = 'customPattern',
  DisableIfEquals = 'disableIfEquals',
  EnableIfEquals = 'enableIfEquals',
  HideIfEmpty = 'hideIfEmpty',
  HideIfNotEqual = 'hideIfNotEqual',
  HideIfParentSiblingEqual = 'hideIfParentSiblingEqual',
  HideIfParentSiblingNotEqual = 'hideIfParentSiblingNotEqual',
  MaxLength = 'maxlength',
  MinLength = 'minlength',
  Max = 'max',
  Min = 'min',
  Alphanumeric = 'alphanumeric',
  Numeric = 'numeric',
  Pattern = 'pattern',
  Required = 'required',
  RequiredIfEquals = 'requiredIfEquals',
  RequiredIfNotEquals = 'requiredIfNotEquals',
  ValidateDefectNotes = 'validateDefectNotes',
  PastDate = 'pastDate',
  CopyValueToRootControl = 'copyValueToRootControl'
}
