version: 1
update_configs:
- package_manager: "javascript"
  directory: "/"
  update_schedule: "live"
  target_branch: "devops"
  version_requirement_updates: increase_versions
  commit_message:
    prefix: "[security-auto]"
  default_reviewers:
  - "irina005"
  - "m-ujaffer"
  - "alleypa"
  default_assignees:
  - "irina005"
  - "m-ujaffer"
  - "alleypa"
  allowed_updates:
  - match:
      update_type: "security"
