import { createFormGroupState } from 'ngrx-forms';
import { adrDetailsFormModel } from './adrDetailsForm.model';
import { IAppState } from './adrDetailsForm.state';

export const adrDetailsFormModelState: adrDetailsFormModel = {
  name: 'test',
  street: 'test',
  town: 'test',
  city: 'test',
  postcode: 'test',
  type: 'test',
  approvalDate: { day: 2, month: 23, year: 1990 },
  permittedDangerousGoods: { ['23']: true },
  compatibilityJ: true,
  additionalNotes: { ['23']: true },
  adrTypeApprovalNo: 'test',
  tankManufacturer: 'test',
  yearOfManufacture: 23,
  tankManufacturerSerialNo: 'test',
  tankTypeAppNo: 'test',
  tankCode: 'test',
  tankDocuments: ['test'],
  substancesPermitted: 'test',
  selectReferenceNumber: 'test',
  statement: 'test',
  productListRefNo: 'test',
  productListUnNo: [23, 123, 411],
  productList: 'test',
  specialProvisions: 'test',
  tc2Type: 'test',
  tc2IntermediateApprovalNo: 'test',
  tc2IntermediateExpiryDate: {
    day: 23,
    month: 12,
    year: 4,
  },
  tc3Type: [12, 42],
  tc3PeriodicNumber: [423],
  tc3PeriodicExpiryDate: [{
    day: 324,
    month: 123,
    year: 123,
  }],
  memosApply: { ['23']: true },
  listStatementApplicable: '',
  batteryListNumber: 'test',
  brakeDeclarationIssuer: 'test',
  brakeEndurance: 'test',
  brakeDeclarationsSeen: 'test',
  declarationsSeen: 'test',
  weight: 23,
  certificateReq: 'test',
  adrMoreDetail: 'test',
};

export const adrDetailsState: IAppState['adrDetails'] = {
  formState: createFormGroupState('adrDetails', adrDetailsFormModelState),
  permittedDangerousGoodsOptions: ['12', '12'],
  additionalNotesOptions: ['12', '123'],
  productListUnNo: { maxIndex: 2, options: adrDetailsFormModelState.productListUnNo },
  tc3Type: { maxIndex: 3, options: [12, 3] },
  tc3PeriodicNumber: { maxIndex: 33, options: [12, 23] },
  tc3PeriodicExpiryDate: { maxIndex: 23, options: [{ day: 2, month: 12, year: 2019 }] },
  tankDocuments: { maxIndex: 523, options: ['23', '214'] },
  submittedValue: adrDetailsFormModelState,
};
