/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdrDetailsTankTankDetailsTc2Details } from './adrDetailsTankTankDetailsTc2Details';
import { AdrDetailsTankTankDetailsTc3Details } from './adrDetailsTankTankDetailsTc3Details';

export interface AdrDetailsTankTankDetails { 
    /**
     * Mandatory. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
     */
    tankManufacturer?: string;
    /**
     * Mandatory. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
     */
    yearOfManufacture?: number;
    /**
     * Mandatory. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
     */
    tankCode?: string;
    /**
     * Optional. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
     */
    specialProvisions?: string;
    /**
     * Mandatory. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
     */
    tankManufacturerSerialNo?: string;
    /**
     * Optional. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
     */
    tankTypeAppNo?: string;
    tc2Details?: AdrDetailsTankTankDetailsTc2Details;
    tc3Details?: Array<AdrDetailsTankTankDetailsTc3Details>;
}