/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AdrDetailsTankTankDetailsTc3Details { 
    /**
     * Optional. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
     */
    tc3Type?: AdrDetailsTankTankDetailsTc3Details.Tc3TypeEnum;
    /**
     * Optional. Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
     */
    tc3PeriodicNumber?: string;
    /**
     * Optional. Date(YYYY-MM-DD). Applicable only if vehicleDetails.type contains the word ‘tank’ or ‘battery’.
     */
    tc3PeriodicExpiryDate?: string;
}
export namespace AdrDetailsTankTankDetailsTc3Details {
    export type Tc3TypeEnum = 'intermediate' | 'periodic' | 'exceptional';
    export const Tc3TypeEnum = {
        Intermediate: 'intermediate' as Tc3TypeEnum,
        Periodic: 'periodic' as Tc3TypeEnum,
        Exceptional: 'exceptional' as Tc3TypeEnum
    };
}