/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AdrDetailsTankTankStatement { 
    /**
     * Mandatory IF vehicleDetails.type contains the word ‘tank’ or ‘battery’ ELSE, optional. If mandatory, users must select ONE of these. Users cannot select less/more than one
     */
    substancesPermitted?: string;
    /**
     * Optional. Applicable only IF vehicleDetails.type contains the word ‘tank’ or ‘battery’
     */
    statement?: string;
    /**
     * Optional. Applicable only IF vehicleDetails.type contains the word ‘tank’ or ‘battery’
     */
    productListRefNo?: string;
    /**
     * Optional. Applicable only IF vehicleDetails.type contains the word ‘tank’ or ‘battery’
     */
    productListUnNo?: Array<string>;
    /**
     * Optional. Applicable only IF vehicleDetails.type contains the word ‘tank’ or ‘battery’
     */
    productList?: string;
}