/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Authorization into service
 */
export interface AuthIntoService { 
    /**
     * Used only for TRL
     */
    cocIssueDate?: string;
    /**
     * Used only for TRL
     */
    dateReceived?: string;
    /**
     * Used only for TRL
     */
    datePending?: string;
    /**
     * Used only for TRL
     */
    dateAuthorised?: string;
    /**
     * Used only for TRL
     */
    dateRejected?: string;
}