/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AxleWeightProperties { 
    /**
     * Used only for PSV
     */
    kerbWeight?: number;
    /**
     * Used only for PSV
     */
    ladenWeight?: number;
    /**
     * Used for all vehicle types - PSV, HGV and TRL
     */
    gbWeight?: number;
    /**
     * Used only for HGV and TRL
     */
    eecWeight?: number;
    /**
     * Used for all vehicle types - PSV, HGV and TRL
     */
    designWeight?: number;
}