/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Letters of authorisation
 */
export interface LettersOfAuth { 
    /**
     * Used only for TRL
     */
    letterType?: LettersOfAuth.LetterTypeEnum;
    /**
     * Used only for TRL
     */
    letterDateRequested?: string;
    /**
     * Used only for TRL
     */
    letterContents?: string;
}
export namespace LettersOfAuth {
    export type LetterTypeEnum = 'Trailer authorization' | 'Trailer rejection';
    export const LetterTypeEnum = {
        Authorization: 'Trailer authorization' as LetterTypeEnum,
        Rejection: 'Trailer rejection' as LetterTypeEnum
    };
}