/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MetadataAdrDetailsTankTankStatement { 
    substancesPermittedFe?: Array<MetadataAdrDetailsTankTankStatement.SubstancesPermittedFeEnum>;
}
export namespace MetadataAdrDetailsTankTankStatement {
    export type SubstancesPermittedFeEnum = 'Substances permitted under the tank code and any special provisions specified in 9 may be carried' | 'Substances (Class UN number and if necessary packing group and proper shipping name) may be carried';
    export const SubstancesPermittedFeEnum = {
        PermittedUnderTheTankCodeAndAnySpecialProvisionsSpecifiedIn9MayBeCarried: 'Substances permitted under the tank code and any special provisions specified in 9 may be carried' as SubstancesPermittedFeEnum,
        ClassUNNumberAndIfNecessaryPackingGroupAndProperShippingNameMayBeCarried: 'Substances (Class UN number and if necessary packing group and proper shipping name) may be carried' as SubstancesPermittedFeEnum
    };
}