/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MetadataAdrDetailsAdditionalNotes } from './metadataAdrDetailsAdditionalNotes';
import { MetadataAdrDetailsTank } from './metadataAdrDetailsTank';
import { MetadataAdrDetailsVehicleDetails } from './metadataAdrDetailsVehicleDetails';

export interface MetadataAdrDetails {
  memosApplyFe?: Array<MetadataAdrDetails.MemosApplyFeEnum>;
  tank?: MetadataAdrDetailsTank;
  additionalNotes?: MetadataAdrDetailsAdditionalNotes;
  permittedDangerousGoodsFe?: Array<MetadataAdrDetails.PermittedDangerousGoodsFeEnum>;
  vehicleDetails?: MetadataAdrDetailsVehicleDetails;
}
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace MetadataAdrDetails {
  export type MemosApplyFeEnum = '07/09 3mth leak ext';
  export const MemosApplyFeEnum = {
    _07093mthLeakExt: '07/09 3mth leak ext' as MemosApplyFeEnum,
  };
  export type PermittedDangerousGoodsFeEnum = 'FP <61 (FL)' | 'AT' | 'Class 5.1 Hydrogen Peroxide (OX)' | 'MEMU' | 'Carbon Disulphide' | 'Hydrogen' | 'Explosives (type 2)' | 'Explosives (type 3)';
  export const PermittedDangerousGoodsFeEnum = {
    FP61FL: 'FP <61 (FL)' as PermittedDangerousGoodsFeEnum,
    AT: 'AT' as PermittedDangerousGoodsFeEnum,
    Class51HydrogenPeroxideOX: 'Class 5.1 Hydrogen Peroxide (OX)' as PermittedDangerousGoodsFeEnum,
    MEMU: 'MEMU' as PermittedDangerousGoodsFeEnum,
    CarbonDisulphide: 'Carbon Disulphide' as PermittedDangerousGoodsFeEnum,
    Hydrogen: 'Hydrogen' as PermittedDangerousGoodsFeEnum,
    ExplosivesType2: 'Explosives (type 2)' as PermittedDangerousGoodsFeEnum,
    ExplosivesType3: 'Explosives (type 3)' as PermittedDangerousGoodsFeEnum,
  };
}
