/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Used for TRL only
 */
export interface PurchaserDetails {
	name?: string;
	address1?: string;
	address2?: string;
	postTown?: string;
	address3?: string;
	postCode?: string;
	emailAddress?: string;
	telephoneNumber?: string;
	faxNumber?: string;
	purchaserNotes?: string;
}
