/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Used for all vehicle types - PSV, HGV, TRL, car, lgv, motorcycle. Optional for CAR and LGV
 */
export interface TechRecordVehicleClass { 
    code?: TechRecordVehicleClass.CodeEnum;
    description?: TechRecordVehicleClass.DescriptionEnum;
}
export namespace TechRecordVehicleClass {
    export type CodeEnum = '2' | 'n' | 's' | '1' | 't' | 'l' | '3' | 'v' | '4' | '7' | '5';
    export const CodeEnum = {
        _2: '2' as CodeEnum,
        N: 'n' as CodeEnum,
        S: 's' as CodeEnum,
        _1: '1' as CodeEnum,
        T: 't' as CodeEnum,
        L: 'l' as CodeEnum,
        _3: '3' as CodeEnum,
        V: 'v' as CodeEnum,
        _4: '4' as CodeEnum,
        _7: '7' as CodeEnum,
        _5: '5' as CodeEnum
    };
    export type DescriptionEnum = 'motorbikes over 200cc or with a sidecar' | 'not applicable' | 'small psv (ie: less than or equal to 22 seats)' | 'motorbikes up to 200cc' | 'trailer' | 'large psv(ie: greater than 23 seats)' | '3 wheelers' | 'heavy goods vehicle' | 'MOT class 4' | 'MOT class 7' | 'MOT class 5' | 'PSV of unknown or unspecified size' | 'Not Known';
    export const DescriptionEnum = {
        MotorbikesOver200ccOrWithASidecar: 'motorbikes over 200cc or with a sidecar' as DescriptionEnum,
        NotApplicable: 'not applicable' as DescriptionEnum,
        SmallPsvIeLessThanOrEqualTo22Seats: 'small psv (ie: less than or equal to 22 seats)' as DescriptionEnum,
        MotorbikesUpTo200cc: 'motorbikes up to 200cc' as DescriptionEnum,
        Trailer: 'trailer' as DescriptionEnum,
        LargePsvIeGreaterThan23Seats: 'large psv(ie: greater than 23 seats)' as DescriptionEnum,
        _3Wheelers: '3 wheelers' as DescriptionEnum,
        HeavyGoodsVehicle: 'heavy goods vehicle' as DescriptionEnum,
        MOTClass4: 'MOT class 4' as DescriptionEnum,
        MOTClass7: 'MOT class 7' as DescriptionEnum,
        MOTClass5: 'MOT class 5' as DescriptionEnum,
        PSVOfUnknownOrUnspecifiedSize: 'PSV of unknown or unspecified size' as DescriptionEnum,
        NotKnown: 'Not Known' as DescriptionEnum
    };
}