/**
 * Vehicles Microservice
 * This is the API spec for the vehicle microservice. Endpoints and parameters only exist for the operations getVehicle and getTechRecords. Other operations within the microservice are out of scope.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bpecete@deloittece.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TechRecordDimensionsAxleSpacing } from './techRecordDimensionsAxleSpacing';

export interface TechRecordDimensions { 
    /**
     * Used for all vehicle types. Optional for PSV
     */
    length?: number;
    /**
     * Used only for PSV
     */
    height?: number;
    /**
     * Used for all vehicle types. Optional for PSV
     */
    width?: number;
    /**
     * Used only for HGV and TRL
     */
    axleSpacing?: Array<TechRecordDimensionsAxleSpacing>;
}