import * as fs from 'node:fs';
import * as path from 'node:path';
import { type Page } from '@playwright/test';
import type { AccessibilityResults, AccessibilityViolation } from 'models/accessibility';

export class AccessibilityMarkdownReporter {
	private readonly results: AccessibilityResults;
	private readonly pageUrl: string;
	private readonly testName: string;

	constructor(results: AccessibilityResults, pageUrl: string, testName: string) {
		this.results = results;
		this.pageUrl = pageUrl;
		this.testName = testName;
	}

	async generateReport(outputPath: string): Promise<string> {
		const markdown = this.generateMarkdown();

		const dir = path.dirname(outputPath);

		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true });
		}

		fs.writeFileSync(outputPath, markdown);

		return outputPath;
	}

	private generateMarkdown(): string {
		const violationCount = this.results.violations.length;
		const impactCounts = this.getImpactCounts();
		const timestamp = new Date().toISOString();

		let markdown = `# ${this.testName}\n\n`;
		markdown += `**URL:** ${this.pageUrl}\n\n`;
		markdown += `**Generated:** ${timestamp}\n\n`;
		markdown += '---\n\n';

		// Summary section
		markdown += '## Summary\n\n';

		if (violationCount === 0) {
			markdown += '### ✅ No Accessibility Violations Found!\n\n';
			markdown += 'This page passed all accessibility checks for the specified WCAG standards.\n\n';
			return markdown;
		}

		// Summary table
		markdown += '| Severity | Count |\n';
		markdown += '|----------|-------|\n';
		markdown += `| 🔴 Critical | ${impactCounts.critical} |\n`;
		markdown += `| 🟠 Serious | ${impactCounts.serious} |\n`;
		markdown += `| 🟡 Moderate | ${impactCounts.moderate} |\n`;
		markdown += `| 🔵 Minor | ${impactCounts.minor} |\n`;
		markdown += `| **Total** | **${violationCount}** |\n\n`;

		markdown += '---\n\n';

		// Violations section
		markdown += '## Violations\n\n';

		const sortedViolations = this.sortViolationsByImpact(this.results.violations);

		for (let i = 0; i < sortedViolations.length; i++) {
			const violation = sortedViolations[i];
			markdown += this.generateViolationMarkdown(violation, i + 1);
		}

		markdown += '---\n\n';
		markdown += '*Generated by [Axe-core](https://www.deque.com/axe/) via Playwright*\n';

		return markdown;
	}

	private generateViolationMarkdown(violation: AccessibilityViolation, index: number): string {
		const impact = violation.impact || 'minor';
		const impactEmoji = this.getImpactEmoji(impact);

		let md = `### ${index}. ${impactEmoji} ${violation.help}\n\n`;
		md += `**Severity:** ${impact.toUpperCase()}\n\n`;
		md += `**Rule ID:** \`${violation.id}\`\n\n`;
		md += `**Description:** ${violation.description}\n\n`;
		md += `**WCAG Reference:** [Learn more about this rule](${violation.helpUrl})\n\n`;

		// Affected elements
		md += `**Affected Elements:** ${violation.nodes.length}\n\n`;

		for (let i = 0; i < violation.nodes.length; i++) {
			const node = violation.nodes[i];
			md += '<details>\n';
			md += `<summary>Element ${i + 1}: <code>${this.escapeMarkdown(node.target.join(' > '))}</code></summary>\n\n`;

			md += '**HTML:**\n\n';
			md += `\`\`\`html\n${node.html}\n\`\`\`\n\n`;

			if (node.failureSummary) {
				md += '**Issue:**\n\n';
				md += `${node.failureSummary}\n\n`;
			}

			md += '</details>\n\n';
		}

		md += '---\n\n';

		return md;
	}

	private getImpactEmoji(impact: string): string {
		const emojiMap: { [key: string]: string } = {
			critical: '🔴',
			serious: '🟠',
			moderate: '🟡',
			minor: '🔵',
		};
		return emojiMap[impact] || '⚪';
	}

	private getImpactCounts(): { critical: number; serious: number; moderate: number; minor: number } {
		const counts = { critical: 0, serious: 0, moderate: 0, minor: 0 };

		for (const violation of this.results.violations) {
			const impact = violation.impact || 'minor';
			if (impact in counts) {
				counts[impact as keyof typeof counts]++;
			}
		}

		return counts;
	}

	private sortViolationsByImpact(violations: AccessibilityViolation[] | unknown): AccessibilityViolation[] {
		if (!violations || !Array.isArray(violations)) {
			return [];
		}

		const impactOrder: { [key: string]: number } = {
			critical: 0,
			serious: 1,
			moderate: 2,
			minor: 3,
		};

		return violations.sort((a, b) => {
			const impactA = impactOrder[a.impact || 'minor'];
			const impactB = impactOrder[b.impact || 'minor'];
			return impactA - impactB;
		});
	}

	private escapeMarkdown(text: string): string {
		return text.replace(/([\\`*_{}[\]()#+\-.!])/g, '\\$1');
	}
}

/**
 * Helper function to generate and save accessibility Markdown report
 */
export async function generateAccessibilityMarkdownReport(
	results: AccessibilityResults,
	page: Page,
	testName: string,
	outputPath?: string
): Promise<string> {
	const url = page.url();
	const defaultPath = outputPath || `test-results/accessibility-reports/${testName}-${Date.now()}.md`;

	const reporter = new AccessibilityMarkdownReporter(results, url, testName);
	return await reporter.generateReport(defaultPath);
}
