#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run security-checks

npx prettier --config .prettierrc --ignore-unknown --write $(git diff --name-only --staged | grep -vF 'src/app/api' | tr '\n' ' ') | grep -o '^\S*' | xargs -I {} git add {}
