name: CI

on:
  push:

jobs:
  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@main
    with:
      args: '--all-projects'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}