name: Build and Deploy VTM App to VTMDev1
run-name: "${{ github.actor }} - ${{ inputs.branch || github.ref_name }} - ${{ github.run_id }} 🚀"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to promote
        required: false
        type: string

jobs:
  vtm-app:
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ inputs.branch || github.ref_name }}
      environment: 'vtmdev-1'
      bucket: '-vtmdev-1.develop'
    secrets:
      AWS_MGMT_ROLE: ${{ secrets.AWS_MGMT_ROLE }}
      AWS_ADMIN_ROLE: ${{ secrets.AWS_NONPROD_ROLE }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
