name: Build and Deploy VTM to VTMDev1
run-name: "${{ github.actor }} - ${{ github.ref_name }} - ${{ github.run_id }} 🚀"

on:
  workflow_dispatch:

jobs:
  feature-build:
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.ref_name }}
      environment: 'vtmdev-1.develop'
    secrets:
      AWS_MGMT_ROLE: ${{ secrets.AWS_MGMT_ROLE }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
