name: Mobile Build
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      branch:
        type: string
        required: true
    secrets:
      AWS_MGMT_ROLE:
        required: true

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Audit
        run: npm audit --audit-level=critical

#      - name: Security checks
#        run: npm run security-checks # git-secrets not available on GHA?

      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_MGMT_ROLE }}
          aws-region: eu-west-1
          role-session-name: GHA-VTMDeploy

      - name: Get app config from AWS Secrets Manager
        run: aws secretsmanager get-secret-value --secret-id ${{ inputs.environment }}/vtm/config --query SecretString --region=eu-west-1 --output text > src/environments/environment.deploy.ts

      - name: downcase BRANCH
        env:
          SHORT_BRANCH: ${{ inputs.branch }}
        run: |
          SHORT_BRANCH=${SHORT_BRANCH##*/}
          echo "SHORT_BRANCH=${SHORT_BRANCH,,}" >>${GITHUB_ENV}

      - name: Update environment config
        if: ${{ inputs.environment == 'feature' }}
        run: |
          ls
          sh "sed  -i\'\' -e \'s/BRANCH/\'${SHORT_BRANCH}\'/g\' src/environments/environment.deploy.ts"

#        Need to pull in/set SENTRY_AUTH_TOKEN value?

      - name: Build
        run: npm run build -- --configuration='deploy' --output-path='dist/'

      - name: Sonar Scanner
        run: npm run sonar-scanner

  deploy_app:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_MGMT_ROLE }}
          aws-region: eu-west-1
          role-session-name: GHA-VTMDeploy

      - name: Deploy App to S3
        working-directory: cvs-app-vtm/dist/
        run: aws s3 sync . s3://vtm-${LBRANCH}.develop.cvs.dvsacloud.uk
