name: VTM Build
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      branch:
        type: string
        required: true
    secrets:
      AWS_MGMT_ROLE:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_MGMT_ROLE }}
          aws-region: eu-west-1
          role-session-name: GHA-VTMDeploy

      - name: Get app config from AWS Secrets Manager
        run: aws secretsmanager get-secret-value --secret-id ${{ inputs.environment }}/vtm/config --query SecretString --region=eu-west-1 --output text > src/environments/environment.deploy.ts

      - name: Make branch lowercase
        env:
          SHORT_BRANCH: ${{ inputs.branch }}
        run: |
          SHORT_BRANCH=${SHORT_BRANCH##*/}
          echo "SHORT_BRANCH=${SHORT_BRANCH,,}" >>${GITHUB_ENV}

      - name: Update environment config
        if: ${{ inputs.environment == 'feature' }}
        run: |
          sed  -i 's/BRANCH/'${SHORT_BRANCH}'/g' src/environments/environment.deploy.ts

      - name: Build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run build -- --configuration='deploy' --output-path='dist/'

#  deploy_infra:
#    needs: [build]
#    name: "Deploy VTM Terraform"
#    runs-on: ubuntu-latest
#    steps:
#      - uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: ${{ secrets.AWS_MGMT_ROLE }}
#          aws-region: "eu-west-1"
#          role-session-name: MGMTGHA
#
#      - uses: aws-actions/aws-secretsmanager-get-secrets@v1
#        with:
#          secret-ids: github/cvs-ops
#          parse-json-secrets: true
#
#      - uses: actions/checkout@v3
#      - name: Start Jobs
#        env:
#          ACTION: "tf-apply"
#          BRANCH: ${{ inputs.branch }}
#          ENVIRONMENT: ${{ inputs.environment }}
#          ACTIONS_KEY: ${{ env.GITHUB_CVS_OPS_TOKEN }}
#        run: python .github/scripts/dispatcher.py

  deploy_app:
    needs: [build]
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_MGMT_ROLE }}
          aws-region: eu-west-1
          role-session-name: GHA-VTMDeploy

      - uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: cvs-app-vtm/gha
          parse-json-secrets: true

      - name: Deploy App to S3
        working-directory: cvs-app-vtm/dist/
        run: aws s3 sync . s3://vtm-${{ inputs.environment }}.${{ env.CVS_APP_VTM_GHA_DOMAIN }}

