name: Build and Deploy VTM App to Develop
run-name: "${{ github.actor }} - ${{ github.ref_name }} - ${{ github.run_id }} 🚀"

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

jobs:
  vtm-app:
    uses: ./.github/workflows/deploy.yml
    with:
      branch: 'develop'
      environment: 'develop'
      bucket: '.develop'
    secrets:
      AWS_MGMT_ROLE: ${{ secrets.AWS_MGMT_ROLE }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
